// bingo tiles

export const tiles = [
  "More megapixels is bettter.",
  "Photoshop/editing is cheating.",
  "AI Art",
  "Multiple phone images to critique.",
  "> asks for feedback, > gets defensive",
  "HDR Confusion",
  "Discord ruined my image",
  "Landscapes, Portraits, Video and some wildlife with $400 budget.",
  "My phone has a 108MP camera.",
  "Snapshot for critique",
  "It's an artistic choice!",
  "Pasta",
  "Stuck on shit advice from family or friend",
  "Stuck on influencer gear rec",
  "Wants a mirrorless camera for no reason.",
  "Is this a good beginner camera? [Insert Canon Rebel here]",
  "I don't have a budget",
  "Wants a full frame camera for no reason",
  "Wants Sony/Fuji for no reason",
  "Source check: Trust me bro",
  "What camera can I get to make really high quality images",
  "What camera makes vintage/retro photos?",
  "Specialists disagree",
  "> Is X camera good? > 10 hours later > Is Y camera good?",
  "I'm scared of used",
  "TikTok/reels advice",
  "Car photography",
  "Nikon people pushing Nikon",
  "Nikon racism",
  "Sigma 150-600",
  "Sigma 100-400",
  "600mm f/4 PF rec",
  "400mm f/2.8 rec",
  "Z6iii will have global shutter",
  "Someone refuses to use prime lenses",
  "Someone refuses to use zoom lenses",
  "ZVE10 rec",
  "This server is so elitist",
  "Un-straightened photo in feedback channel",
  "Are these presets worth [insert cost]",
  "Quag emoji",
  "But [insert Youtuber] said...",
];
